baseURL = "https://blog.sahilister.tech/"
languageCode = "en-us"
title = "sahilister's Reimagined Doodle"
theme = "etch"

enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "thoughts and rambling's"
  copyright = "Copyright © 2020 Sahil Dhiman"
  dark = "auto"
  highlight = true
  
[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10
    
[permalinks]
  posts = "/:year/:month/:title/"

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  ordered = true



